import { type NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";

import FormGroup from "~/components/FormGroup";
import Input from "~/components/Input";

interface GenerateForm {
  prompt: string;
}

const Generate: NextPage = () => {
  const { register, handleSubmit } = useForm<GenerateForm>({
    defaultValues: { prompt: "" },
  });

  const _handleSubmit = (data: GenerateForm) => {
    console.log({ data });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form className="flex flex-col gap-4">
          <FormGroup>
            <label>Prompt</label>
            <Input type="text" {...register("prompt", { required: true })} />
          </FormGroup>

          <button
            className="rounded bg-blue-400 px-4 py-2 hover:bg-blue-500"
            onClick={(e) => {
              e.preventDefault();
              void handleSubmit(_handleSubmit)(e);
            }}
          >
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default Generate;
